In [1]:
import pandas as pd

In [ ]:

df = pd.read_csv("test.csv", sep=",", quotechar='"', engine="python", on_bad_lines="skip")
df.head()

In [9]:
df.isnull().sum()

id               0
title            0
price            0
brand            0
source           0
link             0
image           96
search_query     0
page             0
is_gaming        0
date_scraped     0
currency         0
dtype: int64

In [10]:
df.dropna(inplace=True)

In [11]:
df.isnull().sum()

id              0
title           0
price           0
brand           0
source          0
link            0
image           0
search_query    0
page            0
is_gaming       0
date_scraped    0
currency        0
dtype: int64

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 22205 entries, 0 to 22300
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            22205 non-null  int64
 1   title         22205 non-null  str
 2   price         22205 non-null  float64
 3   brand         22205 non-null  str
 4   source        22205 non-null  str
 5   link          22205 non-null  str
 6   image         22205 non-null  str
 7   search_query  22205 non-null  str
 8   page          22205 non-null  int64
 9   is_gaming     22205 non-null  int64
 10  date_scraped  22205 non-null  str
 11  currency      22205 non-null  str
dtypes: float64(1), int64(3), str(8)
memory usage: 20.9 MB

In [13]:
# 1️⃣ Supprimer les lignes avec price = 0 ou < 1500
df = df[df["price"] >= 1500]

In [14]:
df.info()

<class 'pandas.DataFrame'>
Index: 17376 entries, 0 to 22300
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            17376 non-null  int64
 1   title         17376 non-null  str
 2   price         17376 non-null  float64
 3   brand         17376 non-null  str
 4   source        17376 non-null  str
 5   link          17376 non-null  str
 6   image         17376 non-null  str
 7   search_query  17376 non-null  str
 8   page          17376 non-null  int64
 9   is_gaming     17376 non-null  int64
 10  date_scraped  17376 non-null  str
 11  currency      17376 non-null  str
dtypes: float64(1), int64(3), str(8)
memory usage: 16.3 MB

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:

# 2️⃣ Supprimer les doublons basés sur la colonne 'link'
df = df.drop_duplicates(subset=["link"], keep="first")

In [17]:
df.info()

<class 'pandas.DataFrame'>
Index: 13229 entries, 0 to 22300
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            13229 non-null  int64
 1   title         13229 non-null  str
 2   price         13229 non-null  float64
 3   brand         13229 non-null  str
 4   source        13229 non-null  str
 5   link          13229 non-null  str
 6   image         13229 non-null  str
 7   search_query  13229 non-null  str
 8   page          13229 non-null  int64
 9   is_gaming     13229 non-null  int64
 10  date_scraped  13229 non-null  str
 11  currency      13229 non-null  str
dtypes: float64(1), int64(3), str(8)
memory usage: 12.4 MB

In [18]:
# 3️⃣ Sauvegarder le CSV nettoyé
df.to_csv("products_clean.csv", index=False)

# test_amazon_stand_laptop

In [2]:
df=pd.read_csv('../amazon_laptop_stand.csv')
df

,title,price,currency,brand,category,source,link,image,search_query,page,in_stock,is_gaming,date_scraped
0,GRIFEMA GB1054B Support Ordinateur Portable Ré...,8.99,EUR,GRIFEMA,laptop_stand,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/61u7-I1N0j...,support pc portable,1,True,False,2026-05-02 14:33:06
1,"GRIFEMA Support Ordinateur Portable, Support P...",17.99,EUR,GRIFEMA,laptop_stand,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/61-mNMQSXh...,support pc portable,1,True,False,2026-05-02 14:33:06
2,EWENT EW1258 - Support pour ordinateur portabl...,16.02,EUR,EWENT,laptop_stand,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/61VHoVIhGM...,support pc portable,1,True,False,2026-05-02 14:33:07
3,DIGITUS Support écran - Pince de table - Suppo...,47.41,EUR,DIGITUS,laptop_stand,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/512XeXQg7a...,support pc portable,1,True,False,2026-05-02 14:33:07
4,Fellowes Support PC Portable Everyday – Noir –...,14.99,EUR,Fellowes,laptop_stand,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/81H7HZypeQ...,support pc portable,1,True,False,2026-05-02 14:33:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2614,LogiLink Rehausseur de Moniteur TV Ergonomique...,52.06,EUR,LogiLink,laptop_stand,Amazon,https://www.amazon.fr/Logilink-BP0141-Ergonomi...,https://m.media-amazon.com/images/I/51tqBBKOJM...,rehausseur ecran pc portable,7,True,False,2026-05-02 15:34:35
2615,Support Moniteur Double Support d'angle pour é...,117.99,EUR,Support,laptop_stand,Amazon,https://www.amazon.fr/Moniteur-Organiseur-Ordi...,https://m.media-amazon.com/images/I/51EYat8wXA...,rehausseur ecran pc portable,7,True,False,2026-05-02 15:34:35
2616,Support Moniteur Double Support d'angle pour é...,117.99,EUR,Support,laptop_stand,Amazon,https://www.amazon.fr/Moniteur-Papillon-Ordina...,https://m.media-amazon.com/images/I/71QV8T3Z8l...,rehausseur ecran pc portable,7,True,False,2026-05-02 15:34:35
2617,Support Moniteur Double Support d'angle pour é...,122.99,EUR,Support,laptop_stand,Amazon,https://www.amazon.fr/Acrylique-Transparent-Or...,https://m.media-amazon.com/images/I/61h42iA2Gz...,rehausseur ecran pc portable,7,True,False,2026-05-02 15:34:35
2618,Support Moniteur Double Support d'angle pour é...,119.99,EUR,Support,laptop_stand,Amazon,https://www.amazon.fr/Moniteur-dordinateur-Por...,https://m.media-amazon.com/images/I/7179jgvC22...,rehausseur ecran pc portable,7,True,False,2026-05-02 15:34:35

In [4]:
price_nulll=df[df['price']==0.0]
len(price_nulll)

766

# test_len_clean_amazon_usb

In [6]:
df=pd.read_csv('../usb/amazon_usb_flash_drive.csv')
df

,title,price,currency,brand,category,source,link,image,search_query,page,in_stock,is_gaming,date_scraped
0,"Lexar JumpDrive S80 Clé USB 32 Go, Cle USB 3.2...",12.99,EUR,Lexar,usb_flash_drive,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/71azbH0ywW...,clé usb,1,True,False,2026-05-03 11:30:05
1,SanDisk Ultra Flair 128 Go Flash Drive (Clé US...,24.00,EUR,SanDisk,usb_flash_drive,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/51q1BJpgGk...,clé usb,1,True,False,2026-05-03 11:30:06
2,SanDisk Ultra Luxe 128 Go Flash Drive (Clé USB...,26.25,EUR,SanDisk,usb_flash_drive,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/51jPauko63...,clé usb,1,True,False,2026-05-03 11:30:06
3,"SanDisk Ultra 128 Go Flash Drive, Clé USB 3.0,...",19.58,EUR,SanDisk,usb_flash_drive,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/61T85CGI4Z...,clé usb,1,True,False,2026-05-03 11:30:06
4,"SanDisk 128 Go Cruzer Blade, Clé USB USB 2.0",17.29,EUR,SanDisk,usb_flash_drive,Amazon,https://www.amazon.fr/sspa/click?ie=UTF8&spc=M...,https://m.media-amazon.com/images/I/61DjwgS4cb...,clé usb,1,True,False,2026-05-03 11:30:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4567,Lot de 4 clés USB 3.0 de 32 Go avec adaptateur...,43.90,EUR,Lot,usb_flash_drive,Amazon,https://www.amazon.fr/WesData-adaptateurs-vite...,https://m.media-amazon.com/images/I/71PXrftN8X...,mini clé usb,7,True,False,2026-05-03 13:51:43
4568,Verbatim Store n Go Clé USB avec Adaptateur Na...,0.00,EUR,Verbatim,usb_flash_drive,Amazon,https://www.amazon.fr/Verbatim-Store-avec-Adap...,https://m.media-amazon.com/images/I/61cq67ctge...,mini clé usb,7,True,False,2026-05-03 13:51:43
4569,"Fafeicy Lecteur d' Digitales d'ordinateur, Fas...",0.00,EUR,Fafeicy,usb_flash_drive,Amazon,https://www.amazon.fr/Fafeicy-Digitales-dordin...,https://m.media-amazon.com/images/I/512RpwtX5S...,mini clé usb,7,True,False,2026-05-03 13:51:44
4570,"cobee Dragonne de poignet de petite taille, 12...",16.84,EUR,cobee,usb_flash_drive,Amazon,https://www.amazon.fr/Cobee-Dragonne-r%C3%A9gl...,https://m.media-amazon.com/images/I/71qGVy7pcf...,mini clé usb,7,True,False,2026-05-03 13:51:44
4571,"Lot de 2 boîtes à clés à code à 4 chiffres, mo...",5.16,EUR,Lot,usb_flash_drive,Amazon,https://www.amazon.fr/verrouillage-combinaison...,https://m.media-amazon.com/images/I/61p8ohq7ED...,mini clé usb,7,True,False,2026-05-03 13:51:45

In [10]:
price_nulll=df[df['price']==0.00]
len(price_nulll)

1064